### ISSUE TITLE
Opening a preview within a popup closes the outer popup

### ISSUE THREAD

**Issue by nminchow** [onecrayon/ashes.live#73]
Browser: Firefox, Firefox Mobile Emulator
Devices: Android, Desktop

Clicking a linked card within a card popup on mobile doesn't navigate and instead dismisses the popup. The links function as intended when I request the desktop site on mobile, so I suspect it is something with how specific event types are handled.

Update:

This doesn't seem to be a mobile-only issue, but more an issue of attempting to open a preview within another. The same behavior is exhibited on desktop when you hover over a link within a popup.

**Comment by nminchow** [comment]
From a functionality standpoint, I don't think it'd be terrible to simply do the navigation when this occurs. That is what I expected when I initially attempted this.

**Comment by nminchow** [comment]
I poked at this a little bit. The issue is that the computed property for the parent CardLink is returning `false` before the child is even checked, so the nested popup never ends up checking if it should be displayed.

For clarity, I see 3 functional options here:
1. allow popups to remain open when child popups are open
2. close the old popup and open a new one when when a child link is activated
3. have no hover behavior/first-touch behavior and simply navigate when a child link is clicked

If we opt for option 1 and have multiple popups concurrently, we should probably revert the changes that pushed tracking of this to the store. We could make the state management within the store smarter, but I have a suspicion it will be needlessly complex.

Option 2 is probably do-able if we do something clever and put an intermediary step around `isCurrentTarget` to allow time for the children to be displayed before the parent is dismissed.

3 would be simple, and possibly expected on mobile, but maybe slightly annoying on desktop.

**Comment by onecrayon** [comment]
Hm, it's a tough one. I really like the store approach because it prevents duplicate popups at the root level (something that occurred sometimes prior to this update). But I simultaneously would like to have nested links allow a popup, because the most common scenario for that is looking at a list view in the card browser, and particularly when deck-building navigating away requires you to make a couple of HTTP requests that aren't really desirable.

Would it be possible to do option 1, but by having a boolean property that gets passed to the CardLink when it's created within a popup that would bypass the store in favor of just showing the popup similar to the old functionality? Because realistically, it doesn't matter how far the chain goes, as long as navigating to a new root popup closes everything and starts fresh.

**Comment by nminchow** [comment]
Yeah, we definitely could still leave it in the store. My initial thought would be to make the value stored a list. Then, when a dismissal action is taken, we clear the list, and we push to it when we add.

How would we expect dismissal to work? Do we need to support clearing just the children by clicking "out" on an ancestor?

**Comment by onecrayon** [comment]
> How would we expect dismissal to work? Do we need to support clearing just the children by clicking "out" on an ancestor?

In short, yes. If you tap or move hover into an ancestor, everything opened after that ancestor should close. If you tap or move hover outside the ancestor on the main page, then the whole chain should close.
